"""The default ``config/tools.yaml`` document.

Written by ``operon init`` and merged into every project: launcher defaults
plus the bundled software recipe presets (BLAST tabular, HMMER
tblout/domtblout, BUSCO JSON, RPS-BLAST/rpsbproc tabular).  These presets are
the software-specific boundary that plugin libraries replace; the generic
loader and model live in :mod:`._config`."""

from __future__ import annotations

from typing import Any

DEFAULT_TOOLS_CONFIG: dict[str, Any] = {
    "version": 1,
    "conda": {
        "bin": "conda",
        "run_args": ["run", "--no-capture-output"],
    },
    "tools": {
        "blastn": {
            "description": "NCBI BLAST+ nucleotide-nucleotide search",
            "executable": "blastn",
            "run_method": "conda run --no-capture-output -n blast",
            "version_args": ["-version"],
            "version_pattern": r"blastn:\s*([^\s]+)",
            "recipes": {
                "blastn_nt": {
                    "description": "Assembly FASTA against the NCBI nt database",
                    "entity_type": "assembly",
                    "file_role": "genome_fasta",
                    "format": "fasta",
                    "database": "/path/to/nt",
                    "database_version": "",
                    "output_subdir": "blastn_nt",
                    "output_suffix": ".blastn.tsv",
                    "arguments": [
                        "-db",
                        "${database}",
                        "-query",
                        "${input}",
                        "-out",
                        "${output}",
                        "-outfmt",
                        "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore",
                        "-max_target_seqs",
                        "5",
                        "-evalue",
                        "1e-5",
                        "-num_threads",
                        "${threads}",
                    ],
                    "result_parser": "blast_tabular",
                    "result_columns": [
                        "qseqid",
                        "sseqid",
                        "pident",
                        "length",
                        "mismatch",
                        "gapopen",
                        "qstart",
                        "qend",
                        "sstart",
                        "send",
                        "evalue",
                        "bitscore",
                    ],
                    "hit_metric_columns": ["pident", "length", "evalue", "bitscore"],
                    "max_hits_per_query": 5,
                }
            },
        },
        "blastp": {
            "description": "NCBI BLAST+ protein-protein search",
            "executable": "blastp",
            "run_method": "conda run --no-capture-output -n blast",
            "version_args": ["-version"],
            "version_pattern": r"blastp:\s*([^\s]+)",
            "recipes": {
                "blastp_nr": {
                    "description": "Annotation protein FASTA against nr",
                    "entity_type": "annotation",
                    "file_role": "protein_fasta",
                    "format": "fasta",
                    "database": "/path/to/nr",
                    "database_version": "",
                    "output_subdir": "blastp_nr",
                    "output_suffix": ".blastp.tsv",
                    "arguments": [
                        "-db",
                        "${database}",
                        "-query",
                        "${input}",
                        "-out",
                        "${output}",
                        "-outfmt",
                        "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore",
                        "-max_target_seqs",
                        "5",
                        "-evalue",
                        "1e-5",
                        "-num_threads",
                        "${threads}",
                    ],
                    "result_parser": "blast_tabular",
                    "result_columns": [
                        "qseqid",
                        "sseqid",
                        "pident",
                        "length",
                        "mismatch",
                        "gapopen",
                        "qstart",
                        "qend",
                        "sstart",
                        "send",
                        "evalue",
                        "bitscore",
                    ],
                    "hit_metric_columns": ["pident", "length", "evalue", "bitscore"],
                    "max_hits_per_query": 5,
                }
            },
        },
        "hmmsearch": {
            "description": "HMMER profile search against a protein FASTA",
            "executable": "hmmsearch",
            "version_args": ["-h"],
            "version_pattern": r"HMMER\s+([^\s]+)",
            "recipes": {
                "hmmsearch_pfam": {
                    "description": "Annotation proteins against Pfam-A.hmm",
                    "entity_type": "annotation",
                    "file_role": "protein_fasta",
                    "format": "fasta",
                    "database": "/path/to/Pfam-A.hmm",
                    "database_version": "",
                    "output_subdir": "hmmsearch_pfam",
                    "output_suffix": ".hmmsearch.tblout",
                    "arguments": [
                        "--tblout",
                        "${output}",
                        "--cpu",
                        "${threads}",
                        "${database}",
                        "${input}",
                    ],
                    "result_parser": "hmmer_tblout",
                    "hmmer_mode": "hmmsearch",
                    "max_hits_per_query": 5,
                }
            },
        },
        "busco": {
            "description": "Benchmarking Universal Single-Copy Ortholog assessment",
            "executable": "busco",
            "run_method": "mamba run -n busco_6.1.0",
            "version_args": ["--version"],
            "version_pattern": r"BUSCO\s+([^\s]+)",
            "recipes": {
                "busco_autolineage": {
                    "description": "BUSCO protein mode with automatic lineage selection",
                    "entity_type": "annotation",
                    "file_role": "protein_fasta",
                    "format": "fasta",
                    "input_kind": "file",
                    "database": "resources/busco_downloads",
                    "database_version": "odb12",
                    "database_mode": "mutable_cache",
                    "output_subdir": "busco",
                    "output_kind": "directory",
                    "output_name": "${file_id}.busco",
                    "arguments": [
                        "-m",
                        "protein",
                        "-i",
                        "${input}",
                        "-o",
                        "${output_name}",
                        "--out_path",
                        "${output_parent}",
                        "--download_path",
                        "${database}",
                        "-c",
                        "${threads}",
                        "--auto-lineage",
                        "--opt-out-run-stats",
                        "--tar",
                    ],
                    "result_parser": "busco_json",
                    "result_glob": "short_summary.specific.*.json",
                },
                "busco_lineage": {
                    "description": "BUSCO protein mode with an explicitly selected lineage",
                    "entity_type": "annotation",
                    "file_role": "protein_fasta",
                    "format": "fasta",
                    "input_kind": "file",
                    "parameters": {
                        "lineage_dataset": {
                            "description": "BUSCO lineage dataset name, e.g. fabales_odb12.2",
                            "required": True,
                            "pattern": r"[A-Za-z0-9][A-Za-z0-9_.-]*",
                        }
                    },
                    "database": "resources/busco_downloads",
                    "database_version": "odb12",
                    "database_mode": "mutable_cache",
                    "output_subdir": "busco_lineage",
                    "output_kind": "directory",
                    "output_name": "${file_id}.${lineage_dataset}.busco",
                    "arguments": [
                        "-m",
                        "protein",
                        "-i",
                        "${input}",
                        "-o",
                        "${output_name}",
                        "--out_path",
                        "${output_parent}",
                        "--download_path",
                        "${database}",
                        "--lineage_dataset",
                        "${lineage_dataset}",
                        "-c",
                        "${threads}",
                        "--opt-out-run-stats",
                        "--tar",
                    ],
                    "result_parser": "busco_json",
                    "result_glob": "short_summary.specific.*.json",
                },
            },
        },
        "rpsblast": {
            "description": "NCBI RPS-BLAST against CDD, post-processed by rpsbproc",
            "executable": "rpsblast",
            "run_method": "conda run --no-capture-output -n blast",
            "version_args": ["-version"],
            "version_pattern": r"rpsblast:\s*([^\s]+)",
            "recipes": {
                "rpsblast_cdd": {
                    "description": "Annotation proteins against CDD via rpsblast + rpsbproc",
                    "entity_type": "annotation",
                    "file_role": "protein_fasta",
                    "format": "fasta",
                    "database": "/path/to/cdd/Cdd",
                    "database_version": "",
                    "output_subdir": "rpsblast_cdd",
                    "output_suffix": ".rpsbproc.tsv",
                    "commands": [
                        {
                            "arguments": [
                                "rpsblast",
                                "-query",
                                "${input}",
                                "-db",
                                "${database}",
                                "-out",
                                "${work_dir}/hits.asn",
                                "-outfmt",
                                "11",
                                "-evalue",
                                "0.001",
                                "-num_threads",
                                "${threads}",
                            ],
                        },
                        {
                            "arguments": [
                                "rpsbproc",
                                "-i",
                                "${work_dir}/hits.asn",
                                "-o",
                                "${output}",
                                "-e",
                                "0.001",
                                "-m",
                                "rep",
                            ],
                            "version_args": ["-version"],
                            "version_pattern": r"rpsbproc:\s*([^\s]+)",
                        },
                    ],
                    "result_parser": "rpsbproc_tabular",
                    "max_hits_per_query": 5,
                }
            },
        },
    },
}
